//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDoanKhach
    {
        public int CTDoanKhachId { get; set; }
        public int FkDoan { get; set; }
        public int FkKhachHang { get; set; }
        public string CTDoanKhachTenNguoiDi { get; set; }
        public string CTDoanKhachSdtNguoiDi { get; set; }
        public string CTDoanKhachDiaChiNguoiDi { get; set; }
        public string CTDoanKhachCMNDNguoiDi { get; set; }
    
        public virtual Doan Doan { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
