//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDoanNV
    {
        public int CTDoanNVId { get; set; }
        public int FkDoan { get; set; }
        public int FkNhanVien { get; set; }
        public string CTDoanNVNote { get; set; }
    
        public virtual Doan Doan { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
