//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTour
    {
        public int CTTourId { get; set; }
        public int FkTour { get; set; }
        public int FkDiaDiem { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
