//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.CTDoanKhaches = new HashSet<CTDoanKhach>();
        }
    
        public int KhachHangId { get; set; }
        public string KhachHangTen { get; set; }
        public string KhachHangSdt { get; set; }
        public string KhachHangDiaChi { get; set; }
        public string CMND { get; set; }
        public string KhachHangCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDoanKhach> CTDoanKhaches { get; set; }
    }
}
