//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.CTDoanNVs = new HashSet<CTDoanNV>();
        }
    
        public int NhanVienId { get; set; }
        public string NhanVienCode { get; set; }
        public string NhanVienTen { get; set; }
        public string NhanVienDiaChi { get; set; }
        public string NhanVienSdt { get; set; }
        public string NhanVienCMND { get; set; }
        public int FkLoaiNv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDoanNV> CTDoanNVs { get; set; }
        public virtual LoaiNv LoaiNv { get; set; }
    }
}
